# Generated by Django 6.0.2 on 2026-03-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, max_length=360),
        ),
        migrations.AddField(
            model_name='contactus',
            name='service',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
