# Generated by Django 6.0.2 on 2026-03-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_contactus_options_alter_contactus_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='link',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
