# Generated by Django 6.0.2 on 2026-03-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pix',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
    ]
